analyzer:
  errors:
    invalid_annotation_target: ignore
    depend_on_referenced_packages: ignore
    use_build_context_synchronously: ignore
  exclude:
    - "**/*.arb"
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    library_private_types_in_public_api: false
